{
 "title": "Elasticsearch",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,es_cluster)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "index",
    "label": "index",
    "query": {
     "query": "label_values(elasticsearch_index_stats_search_query_total{es_cluster=~\"$cluster\"},index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",es_cluster=~\"$cluster\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",es_cluster=~\"$cluster\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",es_cluster=~\"$cluster\"}) * 3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "数据节点数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_data_nodes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "专有master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values(\"es_master_node\",elasticsearch_os_cpu_percent{es_data_node=\"false\",es_ingest_node=\"false\",es_master_node=\"true\",es_cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "专有协调节点",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values(\"es_ingest_node\",elasticsearch_os_cpu_percent{es_data_node=\"false\",es_ingest_node=\"true\",es_master_node=\"false\",es_cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "集群索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_stats_indices_count{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "集群文档数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_stats_indices_docs_count{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "活跃分片数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "在线节点总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{es_cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "磁盘剩余量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_available_bytes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "磁盘总量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_size_bytes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "search reject",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{type=\"search\",es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "search queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{type=\"search\",es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "write reject",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{type=\"write\",es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "write queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{type=\"write\",es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "indexing qps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "search qps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-(sum(elasticsearch_filesystem_data_available_bytes{es_cluster=~\"$cluster\"})/sum(elasticsearch_filesystem_data_size_bytes{es_cluster=~\"$cluster\"})))*100"
    }
   ]
  },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "只读索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",write=\"true\"}) "
    }
   ]
  },
  {
   "title": "close索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",state=\"close\"}) "
    }
   ]
  },
  {
   "title": "离线节点总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_node_status{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "lucene_version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{}",
     "legendFormat": "{{lucene_version}}"
    }
   ]
  },
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点在线状态（0-在线，1-离线）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "elasticsearch_cluster_node_status{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "search_qps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_search_query_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "get_qps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_get_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing_qps",
     "type": "timeseries",
     "description": "索引速率",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_indexing_index_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing_qps",
     "type": "timeseries",
     "description": "索引速率",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_indexing_index_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "索引状态(0-green,1-yellow,2-red)趋势",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "索引status",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "max(elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}) by(index,dynamic,number_of_replicas,number_of_shards,creation_date,color)",
       "legendFormat": "{{color}}"
      }
     ]
    },
    {
     "title": "索引可读写性",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "max(elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}) by(index,state,metadata_read,metadata_write,read,write)",
       "legendFormat": "{{color}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Documents indexed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_docs{es_cluster=~\"$cluster\"})",
       "legendFormat": "Documents"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_store_size_bytes{es_cluster=~\"$cluster\"})",
       "legendFormat": "Index Size"
      }
     ]
    },
    {
     "title": "Documents Indexed Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\"}[1h])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Queris/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{es_cluster=~\"$cluster\"}[1h])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Queue Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{es_cluster=~\"$cluster\", type!=\"management\"}) by (type)",
       "legendFormat": "Type: {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{es_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Memory Free",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemFree_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Memory Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemAvailable_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Thread Pools",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_active_count{es_cluster=~\"$cluster\", type!=\"management\"}) by (type)",
       "legendFormat": "Type: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread pool rejections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_thread_pool_rejected_count{es_cluster=~\"$cluster\", type!=\"management\"}[5m])",
       "legendFormat": "{{ name }} {{ type }}"
      }
     ]
    },
    {
     "title": "Avg. CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(irate(node_cpu_seconds_total{cluster=~\"$cluster\"}[60s])) by(mode) *100",
       "legendFormat": "{{ mode }}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "failure_tstamp"
      }
     ]
    },
    {
     "title": "Avg Heap in 15min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",es_cluster=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",es_cluster=~\"$cluster\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "RX/TX Rate 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_transport_rx_packets_total{es_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "RX"
      },
      {
       "expr": "sum(rate(elasticsearch_transport_tx_packets_total{es_cluster=~\"$cluster\"}[5m])) * -1",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "GC seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{es_cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{ name }} {{ gc }}"
      }
     ]
    }
   ]
  }
 ]
}