{
 "title": "Elasticsearch",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,es_cluster)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "index",
    "label": "index",
    "query": {
     "query": "label_values(elasticsearch_index_stats_search_query_total{es_cluster=~\"$cluster\"},index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cluster status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",es_cluster=~\"$cluster\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",es_cluster=~\"$cluster\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",es_cluster=~\"$cluster\"}) * 3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "数据节点数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_data_nodes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "专有master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values(\"es_master_node\",elasticsearch_os_cpu_percent{es_data_node=\"false\",es_ingest_node=\"false\",es_master_node=\"true\",es_cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "专有协调节点",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values(\"es_ingest_node\",elasticsearch_os_cpu_percent{es_data_node=\"false\",es_ingest_node=\"true\",es_master_node=\"false\",es_cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "离线节点总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_node_status{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "在线节点总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{es_cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "活跃分片数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "活跃主分片数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "初始化分片数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "未被分配的分片",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "迁移中的分片",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{es_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "集群文档数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_stats_indices_docs_count{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "集群索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_stats_indices_count{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "green索引数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",color=\"green\"})"
    }
   ]
  },
  {
   "title": "yellow索引数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",color=\"yellow\"})"
    }
   ]
  },
  {
   "title": "red索引数目",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",color=\"red\"})"
    }
   ]
  },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "search reject",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{type=\"search\",es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "write reject",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{type=\"write\",es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "search queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{type=\"search\",es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "write queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{type=\"write\",es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "search reject(count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{type=\"search\",cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "lucene_version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{}",
     "legendFormat": "{{lucene_version}}"
    }
   ]
  },
  {
   "title": "磁盘剩余量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_available_bytes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "磁盘总量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_size_bytes{es_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-(sum(elasticsearch_filesystem_data_available_bytes{es_cluster=~\"$cluster\"})/sum(elasticsearch_filesystem_data_size_bytes{es_cluster=~\"$cluster\"})))*100"
    }
   ]
  },
  {
   "title": "search qps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "indexing qps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "0副本索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\",number_of_replicas=\"0\"})"
    }
   ]
  },
  {
   "title": "只读索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",write=\"true\"}) "
    }
   ]
  },
  {
   "title": "close索引数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_index_health_status{es_cluster=~\"$cluster\",state=\"close\"}) "
    }
   ]
  },
  {
   "title": "cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "查询qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\"}[1m]))by(es_cluster)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\"}[1m]))by(es_cluster)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群活跃节点数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_number_of_nodes{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群活跃数据节点数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_number_of_data_nodes{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群pending_tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群离线节点数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_node_status{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群文档数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_docs{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "活跃分片数目",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_active_shards{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "集群状态(0-green,1-yellow,2-red)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",es_cluster=~\"$cluster\"}) * 0 + scalar(elasticsearch_cluster_health_status{color=\"yellow\",es_cluster=~\"$cluster\"}) * 1 + scalar(elasticsearch_cluster_health_status{color=\"red\",es_cluster=~\"$cluster\"}) * 2",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "活跃主分片数目",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_active_primary_shards{es_cluster=~\"$cluster\"})",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点在线状态（0-在线，1-离线）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "elasticsearch_cluster_node_status{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "elasticsearch_os_cpu_percent{name=~\"$name\", es_cluster=~\"$cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点磁盘总量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "elasticsearch_filesystem_data_size_bytes{es_cluster=~\"$cluster\",name=~\"$name\"}/(1024*1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点磁盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(sum((elasticsearch_filesystem_data_size_bytes{name=~\"$name\",es_cluster=~\"$cluster\"}-elasticsearch_filesystem_data_available_bytes{name=~\"$name\",es_cluster=~\"$cluster\"})/elasticsearch_filesystem_data_size_bytes{name=~\"$name\",es_cluster=~\"$cluster\"})by(es_cluster,name))*100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "HeapMemory使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(sum(elasticsearch_jvm_memory_used_bytes{name=~\"$name\",es_cluster=~\"$cluster\"}/elasticsearch_jvm_memory_max_bytes{name=~\"$name\",es_cluster=~\"$cluster\"})by(es_cluster,name))*100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点磁盘剩余量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "elasticsearch_filesystem_data_available_bytes{es_cluster=~\"$cluster\",name=~\"$name\"}/(1024*1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "熔度次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_breakers_tripped{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点打开的文件句柄数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_process_open_files_count{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "search时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "((delta(elasticsearch_indices_search_query_time_seconds{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])*1000)/delta(elasticsearch_indices_search_query_total{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])) + ((delta(elasticsearch_indices_search_fetch_time_seconds{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])*1000)/delta(elasticsearch_indices_search_fetch_total{es_cluster=~\"$cluster\",name=~\"$name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点进程最大文件描述符",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_process_max_files_descriptors{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "tcp连接数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_transport_server_open{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "indexing时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(delta(elasticsearch_indices_indexing_index_time_seconds_total{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])*1000)/delta(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "节点1分钟负载",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_os_load1{name=~\"$name\", es_cluster=~\"$cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "http连接数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_http_current_open{es_cluster=~\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "15分钟负载",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_os_load15{name=~\"$name\", es_cluster=~\"$cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "5分钟负载",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_os_load5{name=~\"$name\", es_cluster=~\"$cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "设备块写入 count/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_filesystem_io_stats_device_write_operations_count{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "设备块读取 count/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_filesystem_io_stats_device_read_operations_count{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "设备块写入 mb/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_filesystem_io_stats_device_write_size_kilobytes_sum{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])/1024",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "设备块读取 mb/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_filesystem_io_stats_device_read_size_kilobytes_sum{es_cluster=~\"$cluster\",name=~\"$name\"}[1m])/1024",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gc&memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "young GC耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_jvm_gc_collection_seconds_sum{es_cluster=~\"$cluster\",gc=\"young\",name=~\"$name\"}[1m])*1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "old GC耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_jvm_gc_collection_seconds_sum{es_cluster=~\"$cluster\",gc=\"old\",name=~\"$name\"}[1m])*1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "young GC次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_jvm_gc_collection_seconds_count{es_cluster=~\"$cluster\",gc=\"young\",name=~\"$name\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "old GC次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(elasticsearch_jvm_gc_collection_seconds_count{es_cluster=~\"$cluster\",gc=\"old\",name=~\"$name\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "survivor堆内存使用峰值",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{es_cluster=~\"$cluster\",name=~\"$name\",pool=\"survivor\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "young堆内存使用峰值",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{es_cluster=~\"$cluster\",name=~\"$name\",pool=\"young\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "old堆内存使用峰值",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{es_cluster=~\"$cluster\",name=~\"$name\",pool=\"old\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "threadpool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "write线程池reject任务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_thread_pool_rejected_count{name=~\"$name\",es_cluster=~\"$cluster\",type=\"write\"}[1m]))by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "write线程池线程队列大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{name=~\"$name\",es_cluster=~\"$cluster\",type=\"write\"})by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "write线程池active线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_active_count{name=~\"$name\",es_cluster=~\"$cluster\",type=\"write\"})by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "search线程池active线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_active_count{name=~\"$name\",type=\"search\",es_cluster=~\"$cluster\"})by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "search线程池线程队列大小 ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{name=~\"$name\",type=\"search\",es_cluster=~\"$cluster\"})by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "search线程池reject任务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_thread_pool_rejected_count{name=~\"$name\",type=\"search\",es_cluster=~\"$cluster\"}[1m]))by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "rx_packects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_transport_rx_packets_total{name=~\"$name\",es_cluster=~\"$cluster\"}[1m]))by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "tx_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_transport_tx_packets_total{name=~\"$name\",es_cluster=~\"$cluster\"}[1m]))by(es_cluster,name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "rx_packects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "(sum(irate(elasticsearch_transport_tx_size_bytes_total{name=~\"$name\",es_cluster=~\"$cluster\"}[1m]))by(es_cluster,name))/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "rx_packects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "(sum(irate(elasticsearch_transport_rx_size_bytes_total{name=~\"$name\",es_cluster=~\"$cluster\"}[1m]))by(es_cluster,name))/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "search_qps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_search_query_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "get_qps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_get_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing_qps",
     "type": "timeseries",
     "description": "索引速率",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_indexing_index_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing_qps",
     "type": "timeseries",
     "description": "索引速率",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_index_stats_indexing_index_total{es_cluster=~\"$cluster\",index=~\".*\"}[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "索引状态(0-green,1-yellow,2-red)趋势",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "索引status",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "max(elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}) by(index,dynamic,number_of_replicas,number_of_shards,creation_date,color)",
       "legendFormat": "{{color}}"
      }
     ]
    },
    {
     "title": "索引可读写性",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "max(elasticsearch_index_health_status{es_cluster=~\"$cluster\",index=~\".*\"}) by(index,state,metadata_read,metadata_write,read,write)",
       "legendFormat": "{{color}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Documents indexed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_docs{es_cluster=~\"$cluster\"})",
       "legendFormat": "Documents"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_store_size_bytes{es_cluster=~\"$cluster\"})",
       "legendFormat": "Index Size"
      }
     ]
    },
    {
     "title": "Documents Indexed Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{es_cluster=~\"$cluster\"}[1h])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Queris/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{es_cluster=~\"$cluster\"}[1h])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Queue Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{es_cluster=~\"$cluster\", type!=\"management\"}) by (type)",
       "legendFormat": "Type: {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{es_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Memory Free",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemFree_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Memory Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemAvailable_bytes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Thread Pools",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_active_count{es_cluster=~\"$cluster\", type!=\"management\"}) by (type)",
       "legendFormat": "Type: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread pool rejections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_thread_pool_rejected_count{es_cluster=~\"$cluster\", type!=\"management\"}[5m])",
       "legendFormat": "{{ name }} {{ type }}"
      }
     ]
    },
    {
     "title": "Avg. CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(irate(node_cpu_seconds_total{cluster=~\"$cluster\"}[60s])) by(mode) *100",
       "legendFormat": "{{ mode }}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "failure_tstamp"
      }
     ]
    },
    {
     "title": "Avg Heap in 15min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",es_cluster=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",es_cluster=~\"$cluster\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "RX/TX Rate 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_transport_rx_packets_total{es_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "RX"
      },
      {
       "expr": "sum(rate(elasticsearch_transport_tx_packets_total{es_cluster=~\"$cluster\"}[5m])) * -1",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "GC seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{es_cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{ name }} {{ gc }}"
      }
     ]
    }
   ]
  }
 ]
}